version: '2'
services:
    django:
        build: ./docker
        image: nakkat/django
        # container_name: django
        # command: python pepper_attmgt/manage.py runserver 0.0.0.0:8000
        command: bash -c "python pepper_attmgt/manage.py collectstatic --noinput
                            && /usr/local/bin/uwsgi --ini uwsgi.ini"
        volumes:
            - .:/usr/src/app
            - /etc/localtime:/etc/localtime:ro
            - /static
            - /media
        links:
            - mysql
        # ports:
        #     - "8000:8000"
        expose:
            - "5000"
        tty: true
        # user: root
    mysql:
        image: mysql
        volumes:
            - mysql-db:/var/lib/mysql
        ports:
            - "3306:3306"
        hostname: mysql
        environment:
            MYSQL_ROOT_PASSWORD: haralabm1
    nginx:
        image: nginx
        links:
            - django
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            # - ./log:/var/log/nginx
        volumes_from:
            - django
        ports:
            - "80:80"

# driver_opts:
#     type: none
#     device: ./pepper_attmgt/mysql
#     o: bind
volumes:
    mysql-db:
        driver: local
